### ISSUE TITLE
Format the "total interest" value in PayoffProjectionContainer to display as a dollar value

### ISSUE THREAD

**Issue by Tyresius92** [Tyresius92/my-outstanding-balance#27]
**Describe the bug**
Currently, the total interest value in PayoffProjectionContainer displays as a very long float value. 

**Expected behavior**
Update the formatting to display as a dollar value. (i.e. `Total Interest: $123.45`)

**Comment by izhuravlev** [comment]
Hey @Tyresius92,
Can I work on that?

**Comment by Tyresius92** [comment]
Hi @izhuravlev! Sure go for it! Please let me know if you have any questions.

**Comment by izhuravlev** [comment]
Hey @Tyresius92 ,
What configurations do you run Prettier with? Can't make a commit because of the Prettier prechecker.

All in all, my corrections look like this: 
![Capture](https://user-images.githubusercontent.com/36719387/67779879-ad5bcd80-fa3b-11e9-9517-83ed06cd962d.PNG)

**Comment by Tyresius92** [comment]
Hi @izhuravlev Thank you! The PR looks good. Just going to sanity check locally and then I'll merge it in. 

Re: prettier - were you not able to just run prettier on the file? I thought I had it configured to pick up the settings from package.json. Was that not the case?
